transform dtype early
vanvalenlab/deepcell-tracking pull request #42
Opened 2021-01-29 02:56 UTC by Jeff-Gui

In clean_up_annotations(), transform y to int32 at the beginning to avoid overflow when applying new uids to the original matrix.

2021-01-29 19:35 UTC, willgraf commented
Thanks for the PR! It looks good to me but I am now trying to see how to let this PR trigger the Coveralls builds properly.

2021-01-30 01:34 UTC, willgraf requested changes
I've updated our testing workflows to skip the Coveralls report for forked PRs.

Could you please update your PR with the upstream changes to let the CI/CD do the testing?

2021-01-31 11:12 UTC, Jeff-Gui reviewed
Upstream changes have been rebased.

2021-02-01 17:59 UTC, willgraf approved these changes
👍

2021-02-01 17:59 UTC, merged