Update Tracking Approach and Address Outstanding Bugs
vanvalenlab/deepcell-tracking pull request #53
Opened 2021-04-08 21:44 UTC by MekWarrior

## What
* End-to-End updates for DeepCell's approach to the tracking problem in live-cell imaging. A new `Track` object is introduced to hold track information and allow for augmentation using the new dataset builder module in `deepcell-tf`. This PR introduces breaking changes related to the previous LSTM and Siamese Neural Network (SNN) model architecture. The updated `CellTracker` object is intended for use with the `inference` model and `neighborhood` encoders generated and trained by the new graph-based tracking architecture in `deepcell-tf`. Additionally, the utils related to benchmarking have been updated and improved.

## Why
* These updates represent the natural evolution of the repo's approach to tracking. It addresses key needs to further enable adoption of TF2 and dramatically improves tracking speed. At the same time, it address several bugs that have been uncovered since `deepcell-tracking` was first introduced.

2021-04-09 23:23 UTC, willgraf requested changes
Looks pretty good! I would like to take a stab at refactoring some of the code in `tracking.py` - I can send over a PR in a couple of days. In the meantime, please check out the comments, especially in `utils.py` and `isbi_utils.py` and their tests.

2021-04-09 23:23 UTC, willgraf commented on deepcell_tracking/tracking_test.py
> +    #     frames = 5
Just remove the code - no reason to leave it here commented out, we have it in the last releases.

Remove the code from the `tracking.py` too.

2021-04-09 23:23 UTC, willgraf commented on deepcell_tracking/utils.py
> +def normalize_adj_matrix(adj, epsilon=1e-5):
Please include a docstring as well as tests for this function for some basic accuracy stuff. I could easily see this function having a silent error.

2021-04-09 23:23 UTC, willgraf commented on deepcell_tracking/utils.py
> +#       The only difference is usually doing things by batch vs frame
I would prefer to not have duplicate code in `tracking.py` if possible. We should brainstorm the best way to make the code more reusable and flexible.

2021-04-09 23:23 UTC, willgraf commented on deepcell_tracking/tracking.py
> +        self._track_cells = self.track_cells  # backwards compatibility - Is this still neccesary?
No, this is not needed anymore. I think this refactor is a large enough one to justify the breaking change.

2021-04-09 23:23 UTC, willgraf commented on deepcell_tracking/tracking.py
> +    def _get_curr_futr_feats(self, frame, feature_name='embedding'):
I think this method can use a better name.

2021-04-09 23:23 UTC, willgraf commented on deepcell_tracking/tracking.py
> +            self.y[frame][self.y[frame] == old_label] = new_label
If we comment out this update do we get the same results?

2021-04-09 23:23 UTC, willgraf commented on deepcell_tracking/tracking.py
> +                prob = predictions_dict['predictions'][track_id, cell_idx, 2]
We already have the array as a variable, let's use it.

```suggestion
                prob = predictions[track_id, cell_idx, 2]
```

2021-04-09 23:23 UTC, willgraf commented on deepcell_tracking/tracking.py
> +
Just delete this, no reason to keep around. We can just review one of the old releases to compare.

2021-04-10 00:30 UTC, willgraf commented
#35 should take care of a lot of my concerns for the `tracking.py` file. However, while testing it, I found that the tests rarely test a division event. We should definitely try to make sure we can test that workflow.

Also, I would like to change the data format from (batch, cell, frames, ....) to (batch, frames, cells, ...) since we have to use that data input for the neighborhood encoder anyway.

2021-04-13 00:59 UTC, MekWarrior commented on .coveragerc
> +fail_under = 50
Good catch. Returned to 80.

2021-04-13 01:02 UTC, MekWarrior commented on deepcell_tracking/utils.py
> +import cv2
Returned to alphabetical order. Note, however, that it was moved because linter complained about wrong-import-order.

2021-04-13 04:41 UTC, MekWarrior commented on deepcell_tracking/utils.py
> +# from deepcell_toolbox.utils import resize
Now using deepcell-toolbox version. No performance or metric loss.

2021-04-21 19:51 UTC, MekWarrior commented on deepcell_tracking/isbi_utils.py
> +    """Relabel predicted track to match GT track labels.
done

2021-04-22 18:28 UTC, willgraf reviewed
We should try to test a few more functions to improve the coverage/reliability:

- `deepcell_tracking.utils.normalize_adj_matrix`
- `deepcell_tracking.isbi_utils.benchmark_division_performance`
- `deepcell_tracking.utils.concat_tracks`
- `deepcell_tracking.utils.Track`

I'm happy to help with these tests but I think its important we get them in.

2021-04-22 18:28 UTC, willgraf commented on .coveragerc
> +fail_under = 65
We should update this to something higher before we merge to master. Ideally 80%, but IDK if we will get test coverage that high.

2021-04-22 19:32 UTC, MekWarrior commented
One outstanding blocker for this PR is the switch from transposed data. This will also need to be updated in deepcell-tf.

2021-05-05 17:12 UTC, willgraf commented
#57 addresses the switch to time axis first feature data, which is the last outstanding code change for this PR.

I would prefer if we could bring up the test coverage to over 80%, and address some of the questions (with more tests) outlined above.

2021-06-01 22:03 UTC, willgraf approved these changes
Our test coverage for the branch is now at 85%, so I will approve this PR.

That said, there are a few critical pieces of the code that are currently untested:

* `deepcell_tracking.utils.Track` is missing tests for assigning both same and daughter in `temporal_adj_matrix` as well as the invalid (`-1`) values.
* `deepcell_tracking.tracking.CellTracker` is missing several important tests:
  * The entire block of `_update_tracks` that handles new division events
  * The block of `_get_parent` that assigns parents
  * The handling of parents in `_track_to_graph`.
  * False Positive logic in `postprocess` and `_review_candidate_nodes`
  * The entirety of `_remove_false_pos` is untested.
* `deepcell_tracking.isbi_utils.benchmark_division_performance` is untested.

2021-06-01 22:29 UTC, merged